version: 1
secinterval: 5
programs:
- &prog1
  path: "C:\\" # Open with default, so open folder with Explorer
- &cmd
  args:
  path: cmd
schedule:
  oddminute:
    # By addition of 2 we get 1,3,5,...59
    pattern: '* 1-59/2 * * * ? *'
  evenminute:
    pattern: '* 0-59/2 * * * ? *'
  weekday:
    pattern: '* * 4 * * ? *'
    targets:
    - 
      <<: *prog1
      workdir: "C:\\Windows\\"
    timezone: Israel Standard Time
  weekdayUTC:
    # IST = GMT +2/3 based on day save light
    pattern: '* * 2 * * ? *'
    targets:
    - 
      <<: *cmd
      workdir: "C:\\"