version: 1
#secinterval: 5
programs:
- &prog1
  args: '-SpaceAfter '
  path: C:\path\to\program\1.exe
- args: ' -SpaceBefore'
  path: C:\path\to\program\2.exe
- &progcustom2
  args:
  path: C:\path\to\program\3.exe
  workdir: C:\check\im\here
schedule:
  oddminute:
    # By addition of 2 we get 1,3,5,...59
    pattern: '* 1-59/2 * * * ? *'
  evenminute:
    pattern: '* 0-59/2 * * * ? *'
  weekday:
    pattern: '* * * * 45'
    targets:
    - *prog1
    - 
      <<: *progcustom2
      args: " I have both spaces "
    timezone: Jerusalem Daylight Time